ebwiki/ebwiki/wiki/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.syndication.views import feed
from ebwiki.wiki.feeds import LatestEdits
import views # relative import

feeds = {
    'latest': LatestEdits
}

if settings.DEBUG:
    urlpatterns = patterns('',
        (r'^(?P<path>styles.*)$', 'django.views.static.serve', {'document_root': settings.WIKI_DOC_ROOT}),
    )
else:
    urlpatterns = patterns('')

urlpatterns += patterns('',
    (r'^$', views.view_page, {'slug': 'index'}),
    (r'^r/$', views.redirecter),
    (r'^latest-changes/$', views.latest_changes),
    (r'^orphans/$', views.list_orphans),

    (r'^(\w{1,30})/$', views.view_page),
    (r'^(\w{1,30})/edit/$', views.edit_page),
    (r'^(\w{1,30})/history/$', views.history),
    (r'^(\w{1,30})/history/(\d{1,6})/$', views.view_version),
    (r'^(\w{1,30})/history/(\d{1,6})/diff/$', views.previous_version_diff),
    (r'^feeds/(?P<url>.*)/$', feed, {'feed_dict': feeds}),
)

ebwiki/ebwiki/wiki/models.py
from django.db import models
import re

class PageManager(models.Manager):
    def create_with_auto_version(self, slug, headline, content, change_message, change_user, change_ip, minor_edit):
        """
        Creates and returns a Page object with the given attributes.
        Automatically sets version to the next available version number for
        the given slug, in a way that avoids race conditions.
        """
        from django.db import connection
        db_table = self.model._meta.db_table
        cursor = connection.cursor()
        cursor.execute("""
            INSERT INTO %s
                (slug, headline, content, version, change_date, change_message, change_user, change_ip, minor_edit)
            VALUES
                (%%s, %%s, %%s, (SELECT COALESCE(MAX(version), 0) + 1 FROM %s WHERE slug=%%s), NOW(), %%s, %%s, %%s, %%s)""" %\
            (db_table, db_table),
            (slug, headline, content, slug, change_message, change_user, change_ip, minor_edit))
        new_id = connection.ops.last_insert_id(cursor, db_table, 'id')
        connection._commit()
        return self.get(id=new_id)

    def select_all_latest(self):
        """
        Returns a QuerySet of the most recent version of each Page.
        """
        from django.db import connection
        db_table = self.model._meta.db_table
        cursor = connection.cursor()
        cursor.execute("SELECT DISTINCT ON (slug) ID FROM %s ORDER BY slug, version DESC" % db_table)
        return self.filter(id__in=cursor.fetchall())

    def find_orphans(self):
        """
        Returns a list of Pages which aren't linked to by any other Page.
        """
        link_re = re.compile(r'''(?x)
            (?<=\]\() # A link starts with an open paren immediately after a close square bracket
            [^)]+     # Match everything up to the close paren
            (?=\))    # Sanity check: look ahead for the close paren
        ''')
        pages = self.select_all_latest()
        orphans = dict([(p.slug, p) for p in pages])
        for page in pages:
            for slug in link_re.findall(page.content):
                if not slug.startswith("http://"):
                    try:
                        del orphans[slug]
                    except KeyError:
                        pass
        return orphans.values()

class Page(models.Model):
    slug = models.CharField(max_length=30)
    headline = models.CharField(max_length=80)
    content = models.TextField()
    version = models.PositiveIntegerField()
    change_date = models.DateTimeField()
    change_message = models.CharField(max_length=100)
    change_user = models.CharField(max_length=64)
    change_ip = models.IPAddressField()
    minor_edit = models.BooleanField()
    objects = PageManager()

    class Meta:
        unique_together = (('slug', 'version'),)

    def __unicode__(self):
        return self.slug

    def url(self):
        return '/%s/' % self.slug

    def edit_url(self):
        return '/%s/edit/' % self.slug

    def history_url(self):
        return '/%s/history/' % self.slug

    def version_url(self):
        return '/%s/history/%s/' % (self.slug, self.version)

    def diff_url(self):
        return '/%s/history/%s/diff/' % (self.slug, self.version)

ebwiki/ebwiki/wiki/views.py
from django import forms
from django.core.paginator import Paginator, EmptyPage
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render_to_response
from ebwiki.wiki.models import Page
from difflib import unified_diff
import urllib

easy_diff = lambda x, y: '\n'.join(unified_diff(x.split('\n'), y.split('\n'), 'Old page', 'New page', lineterm=""))

class PageForm(forms.Form):
    headline = forms.CharField(max_length=80, widget=forms.TextInput(attrs={'size': 80}))
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 20, 'cols': 70}))
    change_message = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'size': 100}))
    minor_edit = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    version = forms.IntegerField(widget=forms.HiddenInput)

def redirecter(request):
    "Redirects to a given URL without sending the 'Referer' header."
    try:
        url = request.GET['url']
    except KeyError:
        raise Http404
    if not url.startswith('http://') and not url.startswith('https://'):
        raise Http404
    return HttpResponse('<html><head><meta http-equiv="Refresh" content="0; URL=%s"></head><body>Redirecting...</body></html>' % urllib.unquote_plus(url))

def view_page(request, slug):
    try:
        page = Page.objects.order_by('-version').filter(slug=slug)[0]
    except IndexError:
        page = Page(slug=slug) # Temporarily construct Page object so we can call edit_url()
        return HttpResponseRedirect(page.edit_url())
    return render_to_response('wiki/view_page.html', {'page': page})

def view_version(request, slug, version):
    page = get_object_or_404(Page, slug=slug, version=version)
    return render_to_response('wiki/view_version.html', {'page': page})

def edit_page(request, slug):
    try:
        latest_page = Page.objects.order_by('-version').filter(slug=slug)[0]
    except IndexError:
        latest_page = None
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if latest_page:
                if latest_page.headline == cd['headline'] and latest_page.content == cd['content']:
                    # If no changes were made, don't touch the database.
                    return HttpResponseRedirect(latest_page.url())
                if latest_page.version != int(cd['version']):
                    diff = easy_diff(Page.objects.get(slug=slug, version=cd['version']).content, cd['content'])
                    return render_to_response('wiki/edit_conflict.html', {'diff': diff, 'latest_page': latest_page})
            new_page = Page.objects.create_with_auto_version(slug, cd['headline'], cd['content'],
                cd['change_message'], request.META.get('REMOTE_USER', 'anonymous'), request.META['REMOTE_ADDR'],
                cd['minor_edit'])
            return HttpResponseRedirect(new_page.url())
    else:
        if latest_page is not None:
            form = PageForm({'headline': latest_page.headline, 'content': latest_page.content, 'version': latest_page.version})
        else:
            form = PageForm(initial={'change_message': 'Created page', 'version': 0})
    return render_to_response('wiki/edit_page.html', {'old_page': latest_page, 'slug': slug, 'form': form})

def history(request, slug):
    page_list = Page.objects.filter(slug=slug).order_by('-version')
    if not page_list:
        raise Http404("A history doesn't exist for the given slug.")
    return render_to_response('wiki/history.html', {'page_list': page_list, 'slug': slug})

def version_diff(request, slug, version1, version2):
    if int(version1) == 0:
        old_content = ''
    else:
        old_content = get_object_or_404(Page, slug=slug, version=version1).content
    page = get_object_or_404(Page, slug=slug, version=version2)
    diff = easy_diff(old_content, page.content)
    return render_to_response('wiki/version_diff.html', {'diff': diff, 'slug': slug, 'version1': version1, 'version2': version2, 'page': page})

def previous_version_diff(request, slug, version):
    return version_diff(request, slug, int(version)-1, version)

def latest_changes(request):
    p = Paginator(Page.objects.order_by('-change_date'), 30)
    try:
        page_num = int(request.GET.get('p', '1'))
    except ValueError:
        page_num = 1
    try:
        page = p.page(page_num)
    except EmptyPage:
        raise Http404('Invalid page')
    return render_to_response('wiki/latest_changes.html', {'result_page': page})

def list_orphans(request):
    orphans = Page.objects.find_orphans()
    return render_to_response('wiki/list_orphans.html', {'orphans': orphans})

ebwiki/ebwiki/templates/wiki/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
	<title>{% block title %}{% endblock %} | Wiki</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=320; initial-scale=.75; maximum-scale=.75; user-scalable=0;">
	<link rel="alternate" type="application/atom+xml" href="/feeds/latest/" title="Latest wiki edits">
	<link rel="stylesheet" href="/styles/wiki.css" type="text/css" media="all">
	{% block extrahead %}{% endblock %}
</head>
<body>
	{% block header %}
	<div id="header">
		<a id="site-title" href="/">Wiki</a>
		<ul id="site-nav">
			<li><a href="/data/">Data feeds</a></li>
			<li><a href="/latest-changes/">Latest changes</a></li>
		</ul>
	</div>
	{% endblock %}

	<div id="content">
		{% block content %}{% endblock %}
	</div><!--/content-->

	{% block footer %}{% endblock %}
</body>
</html>

ebwiki/ebwiki/templates/wiki/edit_conflict.html
{% extends "wiki/base.html" %}

{% block title %}Conflict!{% endblock %}

{% block content %}

<h1>Conflict!</h1>

<p>Somebody has saved changes to the <strong>{{ latest_page.slug }}</strong> page since the moment you clicked "Edit this page."</p>

<p><a href="{{ latest_page.edit_url }}">Go to this page</a>, then make your changes again. For your convenience, here's a diff of the changes you were about to save:</p>

<pre>
{{ diff }}
</pre>

{% endblock %}

ebwiki/ebwiki/templates/wiki/edit_page.html
{% extends "wiki/base.html" %}

{% block title %}{% if old_page %}Edit {{ old_page.slug }}{% else %}Create {{ slug }}{% endif %}{% endblock %}

{% block extrahead %}
<style type="text/css" media="screen">
	th label { display: block; padding: 0.6em 0; white-space: nowrap; }
	#id_content { line-height: 1.6em; }
	#id_headline,
	#id_content,
	#id_change_message { width: 98%; color: #222; font: 1em Arial, sans-serif; padding: 0.6em 9px; border: 1px solid #ccc; }
	#id_headline { font-weight: bold; }
</style>
{% endblock %}

{% block content %}

{% if old_page %}
<h1>Edit <a href="{{ old_page.url }}">{{ old_page.slug }}</a></h1>
{% else %}
<h1>Create {{ slug }}</h1>
{% endif %}

<form action="" method="post">
	<table>
		{{ form.as_table }}
		<tr class="submit-row"><th>&nbsp;</th><td><input class="button default" type="submit" value="Submit" /></td></tr>
	</table>
</form>

<h3>Markdown key</h3>
<table>
	<tr><td><code>[Link to URL](http://www.example.com/)</code></td><td><a href="http://www.example.com/">Link to URL</a></td></tr>
	<tr><td><code>[Link to wiki page](hello)</code></td><td><a href="/hello/">Link to wiki page</a></td></tr>
</table>
{% endblock %}

ebwiki/ebwiki/templates/wiki/generic_form.html
{% extends "wiki/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<h1>{{ title }}</h1>

<form action="" method="post">
	<table>
		{{ form.as_table }}
		<tr class="submit-row"><th>&nbsp;</th><td><input class="button default" type="submit" value="Submit" /></td></tr>
	</table>
</form>

{% endblock %}

ebwiki/ebwiki/templates/wiki/history.html
{% extends "wiki/base.html" %}

{% block title %}History for {{ slug }}{% endblock %}

{% block content %}

<h1>History for <a href="{{ page_list.0.url }}">{{ slug }}</a></h1>

<table class="history">
	<thead>
		<tr>
			<th>Revision</th>
			<th>Date</th>
			<th>User</th>
			<th>Message</th>
		</tr>
	</thead>
	<tbody>
	{% for page in page_list %}
		<tr>
			<td class="revision"><a class="version button default" href="{{ page.version_url }}">{{ page.version }}</a> <a class="diff button" href="{{ page.diff_url }}">Changes</a></td>			
			<td class="date">{{ page.change_date|date:"F j, Y, P" }}</td>
			<td class="user">{{ page.change_user }}</td>
			<td class="message">{{ page.change_message|escape }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>

{% endblock %}

ebwiki/ebwiki/templates/wiki/latest_changes.html
{% extends "wiki/base.html" %}

{% block title %}Latest changes{% endblock %}

{% block content %}

<h1>Latest changes</h1>

<p>{% if result_page.has_previous %}<a href="?p={{ result_page.previous_page_number }}">Previous</a>{% else %}Previous{% endif %} | {% if result_page.has_next %}<a href="?p={{ result_page.next_page_number }}">Next</a>{% else %}Next{% endif %}</p>

<table class="history latest-changes">
	<thead>
		<tr>
			<th>Page</th>
			<th>Revision</th>
		</tr>
	</thead>
	<tbody>
	{% for page in result_page.object_list %}
		<tr>
			<td class="page">
				<a href="{{ page.url }}">{{ page.headline }}</a>
			</td>
			<td class="revision">
				<a class="version button default" href="{{ page.version_url }}">{{ page.version }}</a> <a class="diff button" href="{{ page.diff_url }}">Changes</a>
				<p class="info">Updated by <span class="user">{{ page.change_user }}</span> <span class="time">{% if page.change_date|timesince %}{{ page.change_date|timesince }} ago{% else %}just now{% endif %}</span></p>
				<p class="message">{{ page.change_message|escape }}</p>
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>

<p>{% if result_page.has_previous %}<a href="?p={{ result_page.previous_page_number }}">Previous</a>{% else %}Previous{% endif %} | {% if result_page.has_next %}<a href="?p={{ result_page.next_page_number }}">Next</a>{% else %}Next{% endif %}</p>

{% endblock %}

ebwiki/ebwiki/templates/wiki/list_orphans.html
{% extends "wiki/base.html" %}

{% block title %}Orphaned pages{% endblock %}

{% block content %}

<h1>Orphaned pages</h1>

<ul>
{% for page in orphans %}
    <li>
        <a href="{{ page.url }}">{{ page.headline }}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

ebwiki/ebwiki/templates/wiki/search.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}Search the wiki{% endblock %}

{% block content %}

<h1>Search the wiki</h1>

<form method="get">
<input type="text" name="query" value="{{ query|escape }}">
<input type="submit" value="Search">
</form>

{% if error %}
<p class="error">
There was an error:
<pre>{{ error }}</pre>
</p>
{% endif %}

{% if results %}
<p>Found {{ total }} result{{ total|pluralize }}.</p>
{% for page in results %}
<p><b><a href="{{ page.url }}">{{ page.headline }}</a></b>
</p>
<p>
{{ page.content|markdown|striptags|truncatewords:20 }}
</p>
{% endfor %}
{% endif %}

{% endblock %}

ebwiki/ebwiki/templates/wiki/version_diff.html
{% extends "wiki/base.html" %}

{% block title %}Changes between versions {{ version1 }} and {{ version2 }} of {{ slug }}{% endblock %}

{% block content %}
<h1>Changes between versions {{ version1 }} and {{ version2 }} of <a href="{{ page.url }}">{{ slug }}</a></h1>

<p class="page-tools">Changes were made by <span class="user">{{ page.change_user }}</span>.</p>

<div class="codeport">
	<pre>{{ diff|escape }}</pre>
</div>
{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools"><a class="button" href="{{ page.history_url }}">Other versions of this page</a> <a class="button default" href="{{ page.url }}">Current version</a></p>
</div>
{% endblock %}

ebwiki/ebwiki/templates/wiki/view_page.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}{{ page.headline|escape }}{% endblock %}

{% block content %}

<h1>{{ page.headline|escape }}</h1>

{{ page.content|markdown|safe }}

{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools">
		<a class="button default" href="{{ page.edit_url }}">Edit</a>
		<a class="button" href="{{ page.history_url }}">View history</a>
		<span class="timestamp"><a href="{{ page.diff_url }}">Last updated</a> by <span class="user">{{ page.change_user }}</span> {% if page.change_date|timesince %}{{ page.change_date|timesince }} ago{% else %}just now{% endif %}.</span>
	</p>
</div><!--/footer-->
{% endblock %}

ebwiki/ebwiki/templates/wiki/view_version.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}Version {{ page.version }} of {{ page.headline|escape }}{% endblock %}

{% block content %}

<h1>Version {{ page.version }} of {{ page.headline|escape }}</h1>

{{ page.content|markdown|safe }}

{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools"><a class="button" href="{{ page.history_url }}">Other versions of this page</a></p>
</div>
{% endblock %}